### ISSUE TITLE
Extracting image features for VQA

### ISSUE THREAD

**Issue by johntiger1** [uclanlp/visualbert#10]
https://github.com/uclanlp/visualbert#extracting-image-features

Could you go into more detail? Should we install the custom pytorch into a new virtual environment, so it doesn't break the pytorch used in training the model? What command do we run with detectron to extract features?

**Comment by liunian-harold-li** [comment]
Hi, thank you for your interest! I installed new virtual environment for detection and the command to extract features is available at https://github.com/uclanlp/visualbert#extract-image-features-on-your-own.

**Comment by yezhengli-Mr9** [comment]
Hi @liunian-harold-li, @johntiger1, how is the speed of extracting image features?

For example, by comparison with one GPU (cpu-only is presumably [not tolerable](https://github.com/airsplay/lxmert/issues/89)), for NLVR2 107,292 images,  [lxmert](https://github.com/airsplay/lxmert) takes 5-6 hours to extract faster-rcnn features by [this caffe](https://github.com/peteanderson80/bottom-up-attention/tree/master/caffe).

**Comment by yezhengli-Mr9** [comment]
> https://github.com/uclanlp/visualbert#extracting-image-features
> 
> Could you go into more detail? Should we install the custom pytorch into a new virtual environment, so it doesn't break the pytorch used in training the model? What command do we run with detectron to extract features?

Hi @johntiger1, if you have not finished this, i am interested in figuring this out as well recently.

**Comment by yezhengli-Mr9** [comment]
> Hi @liunian-harold-li, @johntiger1, how is the speed of extracting image features?
> 
> For example, by comparison with one GPU (cpu-only is presumably [not tolerable](https://github.com/airsplay/lxmert/issues/89)), for NLVR2 107,292 images, [lxmert](https://github.com/airsplay/lxmert) takes 5-6 hours to extract faster-rcnn features by [this caffe](https://github.com/peteanderson80/bottom-up-attention/tree/master/caffe).

Hi @liunian-harold-li, @johntiger1, I get my solution for this question of time estimate and summarize it [here](https://github.com/YIKUAN8/Transformers-VQA/issues/5). Thanks anyway.

**Comment by liunian-harold-li** [comment]
Thank you for testing the time estimate!

**Comment by bigbrother001** [comment]
I find you are all talking about this url:
https://github.com/uclanlp/visualbert#extracting-image-features
while it is a same web of https://github.com/uclanlp/visualbert when I open it, what happened and could anyone tell me something about  https://github.com/uclanlp/visualbert#extracting-image-features?
