### ISSUE TITLE
Pre-training on other BERT models

### ISSUE THREAD

**Issue by Muennighoff** [uclanlp/visualbert#12]
Thanks for the great repo and your efforts! Two quick questions: 

Is there anything that speaks against pre-training VisualBERT with Albert instead of BERT on COCO and then finetune it for downstream tasks? 
Also, I havn't found exact details on what resources are needed for pre-training, except for that it took less than a day on COCO according to your paper - How much hours did it take & what GPUs did you use?

**Comment by liunian-harold-li** [comment]
Hi,
1. I would imagine that using Albert would still work.
2. For most experiments, I do it on 4 1080Ti with 12G memory. Pre-training
on COCO takes less than a day, maybe 18-20 hours? Sorry that I cannot
recall the exact amount of time needed. For experiments on VCR, I used 4
V100s with 16G memory.

**Comment by Muennighoff** [comment]
Okay I see - If I would implement it with Albert, I would have to retrain on COCO right? I cannot just fine-tune using Albert, as the architecture trained on COCO was bert uncased.
