### ISSUE TITLE
ModuleNotFoundError: No module named 'visualbert'

### ISSUE THREAD

**Issue by michelecafagna26** [uclanlp/visualbert#18]
Hi, 
I'm having some troubles running the code. I created a bash script as shown in the readme, but I continue getting this :

Traceback (most recent call last):
  File "train.py", line 23, in <module>
    from visualbert.utils.pytorch_misc import time_batch, save_checkpoint, clip_grad_norm, \
ModuleNotFoundError: No module named 'visualbert'

How can I solve it?

**Comment by dataviral** [comment]
Set the appropriate **PYTHONPATH**. Look at the train command in the README
