### ISSUE TITLE
about MCAN

### ISSUE THREAD

**Issue by ckj1221** [uclanlp/visualbert#19]
![image](https://user-images.githubusercontent.com/59046854/99766333-d6b23480-2b3b-11eb-98b5-0a92f4efc44c.png)
Hello, can you please tell me where can I find the supporting papers (MCAN+VG+Multiple Detectors + BERT) in the last few lines of the table? And whether their code is open source?

**Comment by liunian-harold-li** [comment]
I think it was https://drive.google.com/file/d/1geJTEVMMGs9Y3S2_pZxNzgPMccfYpM_r/view, which is the winner of VQA Challenge 2019.
