### ISSUE TITLE
allennlp 0.8.0 .

### ISSUE THREAD

**Issue by alice-cool** [uclanlp/visualbert#20]
Thanks for your open code

**Comment by alice-cool** [comment]
what is the version of python? pytorch?

**Comment by alice-cool** [comment]
from allennlp.training.trainer import move_optimizer_to_cuda
ImportError: cannot import name 'move_optimizer_to_cuda'

**Comment by alice-cool** [comment]
what is the version of allennlp。 I install the version 1.2.0,but it doesn't know the allennlp.training.trainer import move_optimizer_to_cuda. ?

**Comment by alice-cool** [comment]
from allennlp.training import util as training_util
Ok I found the new document training_util and 
We can write "
     from allennlp.training import util as training_util
  and in the code we write  training_util.move_optimizer_to_cuda

**Comment by alice-cool** [comment]
from allennlp.data.batch import Batch

**Comment by alice-cool** [comment]
> Thanks for your open code



> ```
> from allennlp.training.trainer import move_optimizer_to_cuda
> ```
> 
> ImportError: cannot import name 'move_optimizer_to_cuda'

**Comment by xiaodangao137** [comment]
Hello~ I want to ask how you solved the problem "allennlp.training.trainer import move_optimizer_to_cuda". Thank you very much!!

**Comment by bigbrother001** [comment]
Good job! Thank you very much for the experence, I replace "from allennlp.training.trainer import move_optimizer_to_cuda" with "from allennlp.training.util import move_optimizer_to_cuda" and then it run.
