### ISSUE TITLE
sentence image matching

### ISSUE THREAD

**Issue by goodbai2** [uclanlp/visualbert#21]
Hi, I'm very interested in your work. I'd like to ask how the prediction sentence and image matching of the pre-training task are carried out？Is it in ‘TrainVisualBERTObjective’?I don't quite understand. I'm looking forward to your reply.thank u.

**Comment by liunian-harold-li** [comment]
It is implemented at https://github.com/uclanlp/visualbert/blob/master/pytorch_pretrained_bert/modeling.py#L1471, thanks!
