### ISSUE TITLE
Visual Features Computation

### ISSUE THREAD

**Issue by michelecafagna26** [uclanlp/visualbert#24]
Hi, I'm really interested in your work!, I'd like to ask how exactly the visual features are computed. It would be really useful if you could point me directly to the relative snippet of code. 
Moreover, I would like to ask you to kindly clarify the preprocessing carried out for Flickr's visual feature. In the code, you concatenate additional "spatial features" to the original one coming with an embedding sized 2054 instead of 2048. I couldn't find any explanation in the paper in regard.
Thank you!

**Comment by liunian-harold-li** [comment]
I followed BAN-VQA's implementation for processing the features and I have just updated the script to get the data.
