### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by renmada** [uclanlp/visualbert#30]
visualbert

Can I use models on huggingface model hub do evaluation without fiinetuning, and get mentioned performance in your paper?

1. "uclanlp/visualbert-vqa" evaluate vqa
2.  "uclanlp/visualbert-nlvr2" evaluate nlvr

**Comment by liunian-harold-li** [comment]
Hi thank you for your interest in our work. I did not directly handle the integration into Huggingface but I think it should be possible to use Huggingface code to evaluate on VQA & NLVR2.
