### ISSUE TITLE
Features vqacoco-pre-train

### ISSUE THREAD

**Issue by RitaRamo** [uclanlp/visualbert#31]
Hi,

Thank you for this repo! I would like to know what are the visual features used for the checkpoint: visualbert/configs/vqa/coco-pre-train.json? 

The image features are from which model? Do you have the checkpoint (for example: Detectron e2e_mask_rcnn_R-101-FPN_2x, model_id: 35861858) so that I can use the model with different images?

**Comment by liunian-harold-li** [comment]
Hi I downloaded the features from Pythia (now known as MMF https://github.com/facebookresearch/mmf). I believe this is their script of extracting features https://github.com/allenai/pythia/blob/master/pythia/scripts/features/extract_features.py.
