### ISSUE TITLE
Question about visualBERT

### ISSUE THREAD

**Issue by YuBeomGon** [uclanlp/visualbert#8]
I want to know about the visual token dimension.
linguistic token dimension is 768 which is same with BERT in NLP,
how about visual token?

is there a FCN for visual feature to embedding dimenstion(768)

thanks

**Comment by liunian-harold-li** [comment]
Hi, there is a FCN for projecting visual features at https://github.com/uclanlp/visualbert/blob/master/pytorch_pretrained_bert/modeling.py#L1220. Thanks!
